### ISSUE TITLE
Plugin fails to enable itself in 1.20.4 Pufferfish

### ISSUE THREAD

**Issue by muffinbarde** [Hugo1307/BlockStreet#11] opened 2024-05-06 19:07 UTC
```
[21:02:18 ERROR]: Error occurred while enabling BlockStreet v2.0.0 (Is it up to date?)
java.lang.NullPointerException: null
        at java.util.Objects.requireNonNull(Objects.java:233) ~[?:?]
        at dev.hugog.minecraft.blockstreet.BlockStreet.initializeCompaniesData(BlockStreet.java:170) ~[blockstreet-2.0.0.jar:?]
        at dev.hugog.minecraft.blockstreet.BlockStreet.onEnable(BlockStreet.java:81) ~[blockstreet-2.0.0.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[pufferfish-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:188) ~[pufferfish-1.20.4.jar:git-Pufferfish-49]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[pufferfish-1.20.4.jar:git-Pufferfish-49]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[pufferfish-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:639) ~[pufferfish-1.20.4.jar:git-Pufferfish-49]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:550) ~[pufferfish-1.20.4.jar:git-Pufferfish-49]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:672) ~[pufferfish-1.20.4.jar:git-Pufferfish-49]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:432) ~[pufferfish-1.20.4.jar:git-Pufferfish-49]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:311) ~[pufferfish-1.20.4.jar:git-Pufferfish-49]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1132) ~[pufferfish-1.20.4.jar:git-Pufferfish-49]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[pufferfish-1.20.4.jar:git-Pufferfish-49]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

**Comment by muffinbarde** [comment] 2024-05-06 19:07
Pufferfish is a basic Paper fork btw

**Comment by Hugo1307** [comment] 2024-05-09 22:55
The plugin was only tested with Spigot and Paper. That error is caused by the plugin's inability to find the default company resource. When you install the plugin for the first time, a default company is created; for some reason, the plugin cannot create that company. 

It is probably related to the fact that you are using Pufferfish.

**Comment by muffinbarde** [comment] 2024-05-14 19:01
I just tried it on my Windows PC; I tried Paper as well (later on though) - it somehow does not work; But I should probably test it on a server then

**Comment by Hugo1307** [comment] 2024-05-18 21:01
Please do so. The plugin should work properly on Linux or Mac. I'll close this issue for now; please feel free to re-open it if the problem persists.

**Closed by Hugo1307** 2024-05-18 21:01 UTC
Labels: bug
